const autocompletions = [
    "acetaminophen and codeine",
    "albuterol aerosol",
    "albuterol HFA",
    "alendronate",
    "allopurinol",
    "alprazolam",
    "amitriptyline",
    "amoxicillin",
    "amoxicillin and clavulanate K+",
    "amphetamine and dextroamphetamine XR",
    "atenolol",
    "atorvastatin",
    "azithromycin",
    "benazepril and amlodipine",
    "carisoprodol",
    "carvedilol",
    "cefdinir",
    "celecoxib",
    "cephalexin",
    "ciprofloxacin",
    "citalopram",
    "clonazepam",
    "clonidine HCl",
    "clopidogrel",
    "Premarin (conjugated estrogens)",
    "cyclobenzaprine",
    "diazepam",
    "diclofenac sodium",
    "Yaz (drospirenone and ethinyl estradiol)",
    "Duloxetine",
    "doxycycline hyclate",
    "enalapril",
    "escitalopram",
    "esomeprazole",
    "ezetimibe",
    "fenofibrate",
    "fexofenadine",
    "fluconozole",
    "fluoxetine HCl",
    "fluticasone and salmeterol inhaler",
    "fluticasone nasal spray",
    "folic acid",
    "furosemide",
    "gabapentin",
    "glimepiride",
    "glyburide",
    "glipizide",
    "hydrochlorothiazide",
    "hydrocodone and acetaminophen",
    "ibuprofen",
    "lantus (insulin glargine)",
    "isosorbide mononitrate",
    "lansoprazole",
    "levofloxacin",
    "levothyroxine sodium",
    "synthroid (levothyroxine sodium)",
    "lisinopril and hydrochlorothiazide",
    "lisinopril",
    "lorazepam",
    "losartan",
    "lovastatin",
    "meloxicam",
    "metformin HCl",
    "methylprednisone",
    "metoprolol succinate XL",
    "metoprolol tartrate",
    "mometasone",
    "montelukast",
    "naproxen",
    "omeprazole",
    "oxycodone and acetaminophen",
    "pantoprazole",
    "paroxetine",
    "pioglitazone",
    "potassium chloride",
    "pravastatin",
    "prednisone",
    "pregabalin",
    "promethazine",
    "quetiapine",
    "ranitidine",
    "rosuvastatin",
    "sertraline HCl",
    "viagra (sildenafil HCl)",
    "simvastatin and ezetimibe",
    "simvastatin",
    "spironolactone",
    "sulfamethoxazole and trimethoprim DS",
    "tamsulosin",
    'temezepam',
    "topiramate",
    "tramadol",
    "triamcinolone Ace topical",
    "trazodone HCl",
    "triamterene and hydrochlorothiazide",
    "valaciclovir",
    "valsartan",
    "venlafaxine XR",
    "verapamil SR",
    "zolpidem"
];

export default autocompletions